### POST body
POST http://127.0.0.1:8080/parse
Content-Type: application/json

{
    "name": "john",
    "age": "17"
}

### GET
GET http://127.0.0.1:8080/parse?id=456&thread_id=hello&id=789&thread_id=nihao

### GET
GET http://127.0.0.1:8080/welcome